### PR TITLE
Updating docker file with build step

### PR DESCRIPTION
**Pull request by sarvanand1**

### CODE REVIEW

**Review by trois-six — CHANGES_REQUESTED** [review]
If you want to build the binary inside Docker, I would prefer having a multistage build. 
Something like (not tested):

```
FROM golang AS build

WORKDIR /diagram
COPY . ./
RUN make build

FROM alpine

WORKDIR /
COPY --from=build /diagram/k8s-diagrams /usr/local/bin/k8s-diagrams
USER nonroot:nonroot
ENTRYPOINT ["/usr/local/bin/k8s-diagrams"]
```
And yes, I prefer binaries to be in /usr/local/bin...

**Comment by sarvanand1** [comment]
Makes sense @Trois-Six. Pushed the changes requested.

**Comment by trois-six** [comment]
```
USER nonroot:nonroot
```
was just  an example, but nonroot doesn't exist in alpine. Please replace it with

```
USER nobody:nobody
```

**Comment by trois-six** [comment]
Thank you for your contribution!

**Pull request merged**
